version: "3.7"
 
services:
 
  flask:
    build: ./flask
    container_name: flask
    environment:
      - APP_NAME=FlaskApp
    expose:
      - 8080
    depends_on:
      - db
 
  db:
    image: postgres
    container_name: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
 
 
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
 
    depends_on:
      - flask